const TestData = [  
    { id: 1,
      image:"https://picsum.photos/318/180",
      descriptionImageAltText:'',
      subtitleEnglish: 'Test 1',
      DescriptionEnglish:'Short description here, this is just to see how it would look like with more text and more details',
      DescriptionSpanish:'corta descripcion aqui',
      },
    { id: 2,
      image:"https://picsum.photos/318/180",
      subtitleEnglish: 'Test 2',
      DescriptionEnglish:'Short description here, this is just to see how it would look like with more text and more details. Ideally I would like the button closer to the text',
      DescriptionSpanish:'corta descripcion aqui',
      },
    { id: 3,
      image:"https://picsum.photos/318/180",
      subtitleEnglish: 'Test 3',
      DescriptionEnglish:'Short description here, this is just to see how it would look like with more text and more details. Ideally I would like the button closer to the text',
      DescriptionSpanish:'corta descripcion aqui',
      },
    { id: 4,
      image: "https://picsum.photos/318/180",
      subtitleEnglish: 'Test 4',
      DescriptionEnglish:'Short description here, this is just to see how it would look like with more text and more details. Ideally I would like the button closer to the text',
      DescriptionSpanish:'corta descripcion aqui',
     },
    ]
  
  
  export default TestData;